# This file contains values from Cookiecutter

default_context:
  project_name: "pytest-mock-generator"
  project_description: "A pytest fixture wrapper for https://pypi.org/project/mock-generator"
  organization: "Peter Kogan"
  license: "MIT"
  minimal_python_version: 3.6
  github_name: "pksol"
  email: "kogan.peter@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
